import { AuthorizedClinicalFacts } from './types';

export interface ICUAdmissionFactLockResult {
  passed: boolean;
  message: string;
  unauthorizedICUTerms: string[];
  details: {
    unauthorizedShock: string[];
    unauthorizedSepsis: string[];
    unauthorizedInstability: string[];
    unauthorizedOrganFailure: string[];
    unauthorizedSeverityInterpretation: string[];
    unauthorizedPrognosis: string[];
    unauthorizedDiagnoses: string[];
    unauthorizedPrescriptions: string[];
  };
}

function normalizeText(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * ICUAdmissionFactLock
 * Enforces strict boundaries on ICU admission clinical data generated by AI or external refinement.
 * Prevents AI from inventing or interpreting:
 * - Choque (choque séptico, choque cardiogênico, hipovolêmico, em choque)
 * - Sepse (quadro séptico, septicemia, choque séptico)
 * - Instabilidade (instabilidade hemodinâmica, paciente instável, instabilidade clínica)
 * - Falência orgânica (falência de múltiplos órgãos, falência renal/respiratória/circulatória)
 * - Interpretação de gravidade (alta gravidade, quadro gravíssimo, altíssima gravidade)
 * - Prognóstico (prognóstico reservado, mau prognóstico, prognóstico sombrio)
 * - Diagnósticos médicos ou de enfermagem inventados
 * - Prescrições médicas inventadas
 *
 * Example:
 * Registered: "Noradrenalina 10 mL/h"
 * Allowed: "Em uso de noradrenalina 10 mL/h"
 * Blocked: "Paciente em choque."
 */
export function verifyICUAdmissionFactLock(
  fullRefinedText: string,
  authorizedFacts: AuthorizedClinicalFacts,
  deterministicBaseline: string = ''
): ICUAdmissionFactLockResult {
  const normRefined = normalizeText(fullRefinedText);
  const normBaseline = normalizeText(deterministicBaseline);

  // Collect all text from authorized facts to allow terms explicitly informed by the professional
  const authorizedTexts: string[] = [];
  if (deterministicBaseline) {
    authorizedTexts.push(normBaseline);
  }

  for (const [, category] of Object.entries(authorizedFacts)) {
    if (Array.isArray(category)) {
      for (const fact of category) {
        if (fact.value) {
          if (typeof fact.value === 'string') {
            authorizedTexts.push(normalizeText(fact.value));
          } else if (typeof fact.value === 'object') {
            authorizedTexts.push(normalizeText(JSON.stringify(fact.value)));
          }
        }
        if (fact.canonicalText) {
          authorizedTexts.push(normalizeText(fact.canonicalText));
        }
      }
    }
  }

  const authorizedCorpus = authorizedTexts.join(' ');

  const checkUnauthorized = (pattern: RegExp): string[] => {
    const matches = normRefined.match(pattern);
    if (!matches) return [];
    return matches.filter((match) => !authorizedCorpus.includes(match));
  };

  // 1. Choque
  const shockMatches = checkUnauthorized(
    /\b(choque\s+(?:septico|cardiogenico|hipovolemico|distributivo|obstrutivo|misto|refratario)|em\s+choque|quadro\s+de\s+choque|estado\s+de\s+choque|\bchoque\b)/g
  );

  // 2. Sepse
  const sepsisMatches = checkUnauthorized(
    /\b(sepse(?:\s+grave|\s+de\s+foco|\s+pulmonar|\s+urinaria)?|septicemia|quadro\s+septico|foco\s+septico)\b/g
  );

  // 3. Instabilidade
  const instabilityMatches = checkUnauthorized(
    /\b(instabilidade(?:\s+hemodinamica|\s+ventilatoria|\s+clinica|\s+respiratoria)?|hemodinamicamente\s+instavel|clinicamente\s+instavel|paciente\s+instavel|\binstavel\b)/g
  );

  // 4. Falência orgânica
  const organFailureMatches = checkUnauthorized(
    /\b(falencia(?:\s+organica|\s+de\s+multiplos\s+orgaos|\s+renal|\s+respiratoria|\s+circulatoria|\s+hepatica)?|disfuncao\s+de\s+multiplos\s+orgaos|disfuncao\s+multiplas\s+de\s+orgaos|insuficiencia\s+de\s+multiplos\s+orgaos)\b/g
  );

  // 5. Interpretação de gravidade
  const severityMatches = checkUnauthorized(
    /\b(alta\s+gravidade|altissima\s+gravidade|gravidade\s+extrema|extrema\s+gravidade|quadro\s+gravissimo|estado\s+gravissimo|gravissimo|paciente\s+gravissimo)\b/g
  );

  // 6. Prognóstico
  const prognosisMatches = checkUnauthorized(
    /\b(prognostico(?:\s+reservado|\s+sombrio|\s+mau|\s+favoravel|\s+desfavoravel|\s+incerto)?|mau\s+prognostico|bom\s+prognostico|sem\s+perspectiva|expectativa\s+de\s+vida)\b/g
  );

  // 7. Diagnósticos médicos ou de enfermagem não autorizados
  const diagnosisMatches = checkUnauthorized(
    /\b(diagnostico\s+medico|hipotese\s+diagnostica|diagnostico\s+de\s+enfermagem|diagnosticos\s+de\s+enfermagem)\b/g
  );

  // 8. Prescrições médicas
  const prescriptionMatches = checkUnauthorized(
    /\b(prescricao\s+medica|prescrevo|prescrever|solicito\s+conduta\s+medica|iniciar\s+antibioticoterapia|administrar\s+medicacao\s+conforme\s+prescricao)\b/g
  );

  const unauthorizedTerms: string[] = [
    ...shockMatches,
    ...sepsisMatches,
    ...instabilityMatches,
    ...organFailureMatches,
    ...severityMatches,
    ...prognosisMatches,
    ...diagnosisMatches,
    ...prescriptionMatches,
  ];

  const passed = unauthorizedTerms.length === 0;
  const message = passed
    ? 'ICUAdmissionFactLock: Texto verificado com sucesso sem termos ou inferências não autorizadas.'
    : `ICUAdmissionFactLock bloqueou termos críticos não autorizados: [${unauthorizedTerms.join(', ')}]. A IA não pode inferir choque, sepse, instabilidade, falência orgânica, gravidade, prognóstico ou diagnósticos.`;

  return {
    passed,
    message,
    unauthorizedICUTerms: Array.from(new Set(unauthorizedTerms)),
    details: {
      unauthorizedShock: Array.from(new Set(shockMatches)),
      unauthorizedSepsis: Array.from(new Set(sepsisMatches)),
      unauthorizedInstability: Array.from(new Set(instabilityMatches)),
      unauthorizedOrganFailure: Array.from(new Set(organFailureMatches)),
      unauthorizedSeverityInterpretation: Array.from(new Set(severityMatches)),
      unauthorizedPrognosis: Array.from(new Set(prognosisMatches)),
      unauthorizedDiagnoses: Array.from(new Set(diagnosisMatches)),
      unauthorizedPrescriptions: Array.from(new Set(prescriptionMatches)),
    },
  };
}
