import { AuthorizedClinicalFacts } from './types';

export interface PediatricFactLockResult {
  passed: boolean;
  message: string;
  unauthorizedPediatricTerms: string[];
  details: {
    unauthorizedInterpretations: string[];
    unauthorizedAge: string[];
    unauthorizedWeight: string[];
    unauthorizedHeight: string[];
    unauthorizedGuardian: string[];
    unauthorizedDevelopment: string[];
  };
}

function normalizeText(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * PediatricFactLock
 * Enforces strict boundaries on pediatric clinical data generated by AI or external sources.
 * Prevents AI from inventing or interpreting:
 * - Unrecorded age
 * - Unrecorded weight
 * - Unrecorded height/length
 * - Uninformed guardian/responsible party
 * - Child development milestones / inferences
 * - Expected behavior by age
 * - Percentiles (P50, P10, etc.) and z-scores
 * - Nutritional adequacy / anthropometric calculation (e.g. "peso adequado para a idade", "eutrófico")
 */
export function verifyPediatricFactLock(
  fullRefinedText: string,
  authorizedFacts: AuthorizedClinicalFacts,
  deterministicBaseline: string = ''
): PediatricFactLockResult {
  const normRefined = normalizeText(fullRefinedText);
  const normBaseline = normalizeText(deterministicBaseline);

  // Collect all text from authorized facts
  const authorizedTexts: string[] = [];
  if (deterministicBaseline) {
    authorizedTexts.push(normBaseline);
  }

  let hasAuthorizedAge = false;
  let hasAuthorizedWeight = false;
  let hasAuthorizedHeight = false;
  let hasAuthorizedGuardian = false;

  for (const [categoryKey, category] of Object.entries(authorizedFacts)) {
    if (Array.isArray(category)) {
      for (const fact of category) {
        if (fact.value) {
          if (typeof fact.value === 'string') {
            const normVal = normalizeText(fact.value);
            authorizedTexts.push(normVal);
          } else if (typeof fact.value === 'object') {
            const normVal = normalizeText(JSON.stringify(fact.value));
            authorizedTexts.push(normVal);
          }
        }
        if (fact.canonicalText) {
          authorizedTexts.push(normalizeText(fact.canonicalText));
        }

        // Check if fact is pediatric data
        const idLower = (fact.id || '').toLowerCase();
        const catLower = categoryKey.toLowerCase();
        if (idLower.includes('age') || catLower.includes('age') || idLower.includes('idade')) {
          hasAuthorizedAge = true;
        }
        if (idLower.includes('weight') || catLower.includes('weight') || idLower.includes('peso')) {
          hasAuthorizedWeight = true;
        }
        if (idLower.includes('height') || catLower.includes('height') || idLower.includes('altura') || idLower.includes('comprimento')) {
          hasAuthorizedHeight = true;
        }
        if (idLower.includes('guardian') || idLower.includes('responsavel') || idLower.includes('acompanhante')) {
          hasAuthorizedGuardian = true;
        }
      }
    }
  }

  const allAuthorizedCorpus = authorizedTexts.join(' ');

  // Double check baseline for presence of data
  if (normBaseline.includes('idade:') || normBaseline.includes('anos') || normBaseline.includes('meses')) {
    hasAuthorizedAge = true;
  }
  if (normBaseline.includes('peso:') || normBaseline.includes('kg')) {
    hasAuthorizedWeight = true;
  }
  if (normBaseline.includes('altura:') || normBaseline.includes('comprimento:') || normBaseline.includes('estatura:')) {
    hasAuthorizedHeight = true;
  }
  if (
    normBaseline.includes('acompanhado') ||
    normBaseline.includes('mae') ||
    normBaseline.includes('pai') ||
    normBaseline.includes('responsavel')
  ) {
    hasAuthorizedGuardian = true;
  }

  const unauthorizedInterpretations: string[] = [];
  const unauthorizedDevelopment: string[] = [];
  const unauthorizedAge: string[] = [];
  const unauthorizedWeight: string[] = [];
  const unauthorizedHeight: string[] = [];
  const unauthorizedGuardian: string[] = [];

  // 1. Anthropometric, Nutritional Adequacy & Percentile Interpretations (Strictly prohibited unless explicitly authorized)
  const interpretationPatterns = [
    'adequado para a idade',
    'adequada para a idade',
    'adequado para idade',
    'adequada para idade',
    'adequados para a idade',
    'adequadas para a idade',
    'adequado a idade',
    'adequada a idade',
    'peso adequado',
    'peso normal para a idade',
    'peso normal para idade',
    'peso baixo para a idade',
    'peso baixo para idade',
    'baixo peso',
    'sobrepeso infantil',
    'obesidade infantil',
    'desnutricao infantil',
    'eutrofico',
    'eutrofica',
    'eutrofia',
    'percentil',
    'escore z',
    'escore-z',
    'z-score',
    'z score',
    'calculo antropometrico',
    'antropometria calculada',
    'imc infantil',
    'imc para idade',
    'indice de massa corporal',
    'adequacao nutricional',
    'adequacao antropometrica',
    'dentro do esperado para a idade',
    'esperado para a idade',
    'esperado para sua idade',
    'esperada para a idade',
  ];

  for (const pattern of interpretationPatterns) {
    if (normRefined.includes(pattern)) {
      if (!allAuthorizedCorpus.includes(pattern)) {
        unauthorizedInterpretations.push(pattern);
      }
    }
  }

  // 2. Child Development & Expected Behavior Inferences
  const developmentPatterns = [
    'desenvolvimento esperado',
    'desenvolvimento adequado',
    'desenvolvimento neuropsicomotor',
    'dnpm esperado',
    'dnpm adequado',
    'marcos do desenvolvimento',
    'marcos de desenvolvimento',
    'compativel com a faixa etaria',
    'compativel com a idade',
    'comportamento esperado',
    'comportamento esperado para a idade',
    'esperado para o desenvolvimento',
    'apto para a idade',
    'atraso no desenvolvimento',
    'regressao no desenvolvimento',
  ];

  for (const dev of developmentPatterns) {
    if (normRefined.includes(dev)) {
      if (!allAuthorizedCorpus.includes(dev)) {
        unauthorizedDevelopment.push(dev);
      }
    }
  }

  // 3. Unrecorded or Altered Age Detection
  const ageMatches = normRefined.match(/\b\d+\s*(mes|meses|ano|anos|dias|semanas)\b/gi) || [];
  for (const am of ageMatches) {
    if (!allAuthorizedCorpus.includes(am)) {
      unauthorizedAge.push(am);
    }
  }

  // 4. Unrecorded or Altered Weight Detection
  const weightMatches = normRefined.match(/\b\d+(\.\d+)?\s*(kg|quilos)\b/gi) || [];
  for (const wm of weightMatches) {
    if (!allAuthorizedCorpus.includes(wm)) {
      unauthorizedWeight.push(wm);
    }
  }

  // 5. Unrecorded or Altered Height Detection
  const heightMatches = normRefined.match(/\b\d+(\.\d+)?\s*(cm|centimetros)\b/gi) || [];
  for (const hm of heightMatches) {
    if (!allAuthorizedCorpus.includes(hm)) {
      unauthorizedHeight.push(hm);
    }
  }

  // 6. Unrecorded Guardian Detection
  if (!hasAuthorizedGuardian) {
    const guardianPatterns = [
      'acompanhado por',
      'acompanhada por',
      'presenca da mae',
      'presenca do pai',
      'presenca do responsavel',
      'ao lado da mae',
      'ao lado do pai',
      'no colo da mae',
      'no colo do pai',
    ];
    for (const gp of guardianPatterns) {
      if (normRefined.includes(gp) && !allAuthorizedCorpus.includes(gp)) {
        unauthorizedGuardian.push(gp);
      }
    }
  }

  const allUnauthorized = [
    ...unauthorizedInterpretations,
    ...unauthorizedDevelopment,
    ...unauthorizedAge,
    ...unauthorizedWeight,
    ...unauthorizedHeight,
    ...unauthorizedGuardian,
  ];

  const passed = allUnauthorized.length === 0;
  let message = 'PediatricFactLock: Validação concluída sem infrações.';

  if (!passed) {
    const reasons: string[] = [];
    if (unauthorizedInterpretations.length > 0) {
      reasons.push(`Interpretações antropométricas/nutricionais/percentis não autorizadas: [${unauthorizedInterpretations.join(', ')}]`);
    }
    if (unauthorizedDevelopment.length > 0) {
      reasons.push(`Inferências sobre desenvolvimento infantil/comportamento esperado: [${unauthorizedDevelopment.join(', ')}]`);
    }
    if (unauthorizedAge.length > 0) {
      reasons.push(`Idade não registrada nos fatos clínicos foi introduzida: [${unauthorizedAge.join(', ')}]`);
    }
    if (unauthorizedWeight.length > 0) {
      reasons.push(`Peso não registrado nos fatos clínicos foi introduzido: [${unauthorizedWeight.join(', ')}]`);
    }
    if (unauthorizedHeight.length > 0) {
      reasons.push(`Altura não registrada nos fatos clínicos foi introduzida: [${unauthorizedHeight.join(', ')}]`);
    }
    if (unauthorizedGuardian.length > 0) {
      reasons.push(`Responsável/acompanhante não informado foi introduzido: [${unauthorizedGuardian.join(', ')}]`);
    }
    message = `PediatricFactLock: ${reasons.join(' | ')}`;
  }

  return {
    passed,
    message,
    unauthorizedPediatricTerms: allUnauthorized,
    details: {
      unauthorizedInterpretations,
      unauthorizedAge,
      unauthorizedWeight,
      unauthorizedHeight,
      unauthorizedGuardian,
      unauthorizedDevelopment,
    },
  };
}
