import { AuthorizedClinicalFacts } from './types';

export interface SurgicalFactLockResult {
  passed: boolean;
  message: string;
  unauthorizedSurgicalTerms: string[];
  details: {
    unauthorizedProcedures: string[];
    unauthorizedTiming: string[];
    unauthorizedAnesthesia: string[];
    unauthorizedDrains: string[];
    unauthorizedComplications: string[];
    unauthorizedMaterials: string[];
  };
}

function normalizeText(str: string): string {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/**
 * SurgicalFactLock
 * Enforces strict boundaries on surgical details generated by AI or external sources.
 * Prevents AI from inventing:
 * - Surgical procedures / names of surgery (e.g., laparotomia, colecistectomia, apendicectomia)
 * - Timing of surgery (pós-operatório, pré-operatório)
 * - Anesthesia types (geral, raquidiana, peridural, etc.)
 * - Surgical complications (deiscência, evisceração, infecção de ferida operatória, fístula, etc.)
 * - Surgical drains (Portovac, Penrose, dreno tubular, etc.)
 * - Surgical prostheses or materials (tela de marlex, prótese, etc.)
 */
export function verifySurgicalFactLock(
  fullRefinedText: string,
  authorizedFacts: AuthorizedClinicalFacts,
  deterministicBaseline: string = ''
): SurgicalFactLockResult {
  const normRefined = normalizeText(fullRefinedText);
  const normBaseline = normalizeText(deterministicBaseline);

  // Collect all text from authorized facts
  const authorizedTexts: string[] = [];
  if (deterministicBaseline) {
    authorizedTexts.push(normBaseline);
  }

  for (const category of Object.values(authorizedFacts)) {
    if (Array.isArray(category)) {
      for (const fact of category) {
        if (fact.value) {
          if (typeof fact.value === 'string') {
            authorizedTexts.push(normalizeText(fact.value));
          } else if (typeof fact.value === 'object') {
            authorizedTexts.push(normalizeText(JSON.stringify(fact.value)));
          }
        }
        if (fact.canonicalText) {
          authorizedTexts.push(normalizeText(fact.canonicalText));
        }
      }
    }
  }

  const allAuthorizedCorpus = authorizedTexts.join(' ');

  const unauthorizedProcedures: string[] = [];
  const unauthorizedTiming: string[] = [];
  const unauthorizedAnesthesia: string[] = [];
  const unauthorizedDrains: string[] = [];
  const unauthorizedComplications: string[] = [];
  const unauthorizedMaterials: string[] = [];

  // 1. Surgical Procedures & Surgery Names
  const surgicalProcedurePatterns = [
    'laparotomia',
    'laparoscopia',
    'apendicectomia',
    'colecistectomia',
    'herniorrafia',
    'gastrectomia',
    'colectomia',
    'artroplastia',
    'artrodese',
    'osteossintese',
    'craniotomia',
    'traqueostomia',
    'mastectomia',
    'histerectomia',
    'amputacao',
    'revascularizacao',
    'angioplastia',
    'desbridamento cirurgico',
    'toracotomia',
    'enterectomia',
    'esplenectomia',
    'nefrectomia',
    'tireoidectomia',
    'prostatectomia',
    'safenectomia',
    'traqueostomia',
    'traqueotomia',
  ];

  for (const proc of surgicalProcedurePatterns) {
    if (normRefined.includes(proc)) {
      if (!allAuthorizedCorpus.includes(proc)) {
        unauthorizedProcedures.push(proc);
      }
    }
  }

  // 2. Surgical Timing / Situations
  const timingPatterns = [
    { pattern: 'pos-operatorio', label: 'pós-operatório' },
    { pattern: 'pre-operatorio', label: 'pré-operatório' },
    { pattern: 'poi', label: 'POI' },
    { pattern: 'pom', label: 'POM' },
    { pattern: 'pot', label: 'POT' },
  ];

  for (const t of timingPatterns) {
    if (new RegExp(`\\b${t.pattern}\\b`, 'i').test(normRefined)) {
      if (!allAuthorizedCorpus.includes(t.pattern)) {
        unauthorizedTiming.push(t.label);
      }
    }
  }

  // 3. Anesthesia Types
  const anesthesiaPatterns = [
    { pattern: 'anestesia geral', label: 'anestesia geral' },
    { pattern: 'raquianestesia', label: 'raquianestesia' },
    { pattern: 'raquidiana', label: 'raquidiana' },
    { pattern: 'peridural', label: 'peridural' },
    { pattern: 'anestesia local', label: 'anestesia local' },
    { pattern: 'bloqueio anestesico', label: 'bloqueio anestésico' },
  ];

  for (const a of anesthesiaPatterns) {
    if (normRefined.includes(a.pattern)) {
      if (!allAuthorizedCorpus.includes(a.pattern)) {
        unauthorizedAnesthesia.push(a.label);
      }
    }
  }

  // 4. Surgical Drains
  const drainPatterns = [
    { pattern: 'portovac', label: 'Portovac' },
    { pattern: 'penrose', label: 'Penrose' },
    { pattern: 'dreno tubular', label: 'Dreno tubular' },
    { pattern: 'dreno de torax', label: 'Dreno de tórax' },
    { pattern: 'dreno toracico', label: 'Dreno torácico' },
    { pattern: 'jackson-pratt', label: 'Jackson-Pratt' },
    { pattern: 'jackson pratt', label: 'Jackson-Pratt' },
    { pattern: 'blake', label: 'Dreno Blake' },
    { pattern: 'hemovac', label: 'Hemovac' },
    { pattern: 'dreno de kehr', label: 'Dreno de Kehr' },
  ];

  for (const d of drainPatterns) {
    if (normRefined.includes(d.pattern)) {
      if (!allAuthorizedCorpus.includes(d.pattern)) {
        unauthorizedDrains.push(d.label);
      }
    }
  }

  // 5. Surgical Complications
  const complicationPatterns = [
    { pattern: 'deiscencia', label: 'deiscência' },
    { pattern: 'evisceracao', label: 'evisceração' },
    { pattern: 'infeccao de sitio cirurgico', label: 'infecção de sítio cirúrgico' },
    { pattern: 'infeccao da ferida', label: 'infecção da ferida operatória' },
    { pattern: 'necrose cirurgica', label: 'necrose cirúrgica' },
    { pattern: 'fistula', label: 'fístula' },
    { pattern: 'sangramento ativo', label: 'sangramento ativo' },
    { pattern: 'choque hipovolemico', label: 'choque hipovolêmico' },
    { pattern: 'sepse', label: 'sepse' },
    { pattern: 'peritonite', label: 'peritonite' },
  ];

  for (const c of complicationPatterns) {
    if (normRefined.includes(c.pattern)) {
      if (!allAuthorizedCorpus.includes(c.pattern)) {
        unauthorizedComplications.push(c.label);
      }
    }
  }

  // 6. Surgical Materials / Prostheses
  const materialPatterns = [
    { pattern: 'protese', label: 'prótese' },
    { pattern: 'ortese', label: 'órtese' },
    { pattern: 'tela de marlex', label: 'tela de marlex' },
    { pattern: 'tela de polipropileno', label: 'tela de polipropileno' },
    { pattern: 'marcapasso epicardico', label: 'marcapasso epicárdico' },
  ];

  for (const m of materialPatterns) {
    if (normRefined.includes(m.pattern)) {
      if (!allAuthorizedCorpus.includes(m.pattern)) {
        unauthorizedMaterials.push(m.label);
      }
    }
  }

  const allUnauthorized = [
    ...unauthorizedProcedures,
    ...unauthorizedTiming,
    ...unauthorizedAnesthesia,
    ...unauthorizedDrains,
    ...unauthorizedComplications,
    ...unauthorizedMaterials,
  ];

  const passed = allUnauthorized.length === 0;
  const message = passed
    ? 'SurgicalFactLock: Nenhum fato cirúrgico não autorizado detectado.'
    : `SurgicalFactLock violação: fatos cirúrgicos não registrados foram detectados no texto: [${allUnauthorized.join(', ')}].`;

  return {
    passed,
    message,
    unauthorizedSurgicalTerms: allUnauthorized,
    details: {
      unauthorizedProcedures,
      unauthorizedTiming,
      unauthorizedAnesthesia,
      unauthorizedDrains,
      unauthorizedComplications,
      unauthorizedMaterials,
    },
  };
}
